/**
 * @author drbc
 */
/**
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values 
*   do not exceed four million, find the sum of the even-valued terms.
 */
package projecteuler2;

/**
 *
 * @author drbc
 */
public class ProjectEuler2 {
    public static void main(String[] args) {
         long prev1=1;
         long prev2=2;
         long current =0;
         long sum=0;
         while ((current = prev1 + prev2)<=4000000) {      
             if (isEven(current)) sum+=current;
             prev1 = prev2;
             prev2 = current;
             System.out.println("Item: "+current);
         }
         sum+=2;
         System.out.print("\n Sum "+sum);
    }
    
    private static boolean isEven(long number){
        if ((number % 2)==0) {
            return true;
        }
        return false;
    }
}
